name: ship_management
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.1.1
  equatable: ^2.0.5
  mapsforge_flutter:
    path: ./mapsforge_flutter
  flutter_svg: ^2.0.5
  shared_preferences: ^2.0.13
  wakelock: ^0.6.2
  intl: ^0.17.0
  location: ^4.4.0
  dropdown_search: ^5.0.6
  collection: ^1.17.0
  realm: ^1.0.3
  omni_datetime_picker: ^1.0.2
  url_launcher: ^6.1.5
  async: ^2.4.1
  archive: ^3.3.7
  flutter_archive: ^5.0.0
  leak_tracker: ^3.0.1
  # BSD License
  logging: ^1.1.1
  rxdart: ^0.27.7
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^14.0.1
  device_info_plus:
  flutter_background_service_ios: ^2.4.0
  flutter_background_service_android: ^3.0.2
  latlong2: ^0.8.1
  flutter_map:
  vector_mbtiles: ^0.0.5
  vector_tile_renderer: ^3.0.4
  vector_map_tiles: ^3.1.4
  path: ^1.8.1
  file_picker:
  dropdown_button2: ^2.1.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  pedantic_mono: ^1.20.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/thongtintau.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/render_themes/
    - assets/
